/**
 * Japan Travel Catalog Data
 * 50 curated locations across Tokyo, Kyoto, Osaka
 * Includes public data (made-up) + user-generated fields
 */

const locations = [
  // ─── TOKYO (18 locations) ───────────────────────────────────────────────────
  {
    id: 1,
    name: "Shibuya Crossing",
    city: "Tokyo",
    type: "City",
    crowdLevel: "High",
    bestTime: "Night",
    publicRating: 4.8,
    publicImage: "images/tokyo/shibuya-crossing.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 2,
    name: "Senso-ji Temple",
    city: "Tokyo",
    type: "Temple",
    crowdLevel: "High",
    bestTime: "Morning",
    publicRating: 4.7,
    publicImage: "images/tokyo/sensoji.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 3,
    name: "Shinjuku Gyoen",
    city: "Tokyo",
    type: "Park",
    crowdLevel: "Medium",
    bestTime: "Morning",
    publicRating: 4.7,
    publicImage: "images/tokyo/shinjuku-gyoen.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 4,
    name: "Meiji Shrine",
    city: "Tokyo",
    type: "Shrine",
    crowdLevel: "Medium",
    bestTime: "Morning",
    publicRating: 4.6,
    publicImage: "images/tokyo/meiji-shrine.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 5,
    name: "Tokyo Skytree",
    city: "Tokyo",
    type: "Landmark",
    crowdLevel: "High",
    bestTime: "Afternoon",
    publicRating: 4.5,
    publicImage: "images/tokyo/skytree.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 6,
    name: "Tsukiji Outer Market",
    city: "Tokyo",
    type: "Market",
    crowdLevel: "High",
    bestTime: "Morning",
    publicRating: 4.5,
    publicImage: "images/tokyo/tsukiji.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 7,
    name: "Akihabara Electric Town",
    city: "Tokyo",
    type: "District",
    crowdLevel: "High",
    bestTime: "Afternoon",
    publicRating: 4.4,
    publicImage: "images/tokyo/akihabara.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 8,
    name: "Harajuku Takeshita Street",
    city: "Tokyo",
    type: "District",
    crowdLevel: "High",
    bestTime: "Afternoon",
    publicRating: 4.3,
    publicImage: "images/tokyo/takeshita.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 9,
    name: "Odaiba",
    city: "Tokyo",
    type: "Island",
    crowdLevel: "Medium",
    bestTime: "Evening",
    publicRating: 4.3,
    publicImage: "images/tokyo/odaiba.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 10,
    name: "Ueno Park",
    city: "Tokyo",
    type: "Park",
    crowdLevel: "Medium",
    bestTime: "Morning",
    publicRating: 4.4,
    publicImage: "images/tokyo/ueno-park.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 11,
    name: "Yanaka Ginza",
    city: "Tokyo",
    type: "District",
    crowdLevel: "Low",
    bestTime: "Afternoon",
    publicRating: 4.4,
    publicImage: "images/tokyo/yanaka.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 12,
    name: "teamLab Borderless",
    city: "Tokyo",
    type: "Museum",
    crowdLevel: "Medium",
    bestTime: "Afternoon",
    publicRating: 4.8,
    publicImage: "images/tokyo/teamlab.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 13,
    name: "Roppongi Hills",
    city: "Tokyo",
    type: "City",
    crowdLevel: "Medium",
    bestTime: "Evening",
    publicRating: 4.3,
    publicImage: "images/tokyo/roppongi-hills.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 14,
    name: "Tokyo DisneySea",
    city: "Tokyo",
    type: "Amusement Park",
    crowdLevel: "High",
    bestTime: "Morning",
    publicRating: 4.9,
    publicImage: "images/tokyo/disneysea.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 15,
    name: "Shinjuku Golden Gai",
    city: "Tokyo",
    type: "District",
    crowdLevel: "High",
    bestTime: "Night",
    publicRating: 4.5,
    publicImage: "images/tokyo/golden-gai.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 16,
    name: "Yoyogi Park",
    city: "Tokyo",
    type: "Park",
    crowdLevel: "Medium",
    bestTime: "Afternoon",
    publicRating: 4.4,
    publicImage: "images/tokyo/yoyogi.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 17,
    name: "Jimbocho Book Town",
    city: "Tokyo",
    type: "District",
    crowdLevel: "Low",
    bestTime: "Afternoon",
    publicRating: 4.3,
    publicImage: "images/tokyo/jimbocho.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 18,
    name: "Nakameguro Canal",
    city: "Tokyo",
    type: "Waterfront",
    crowdLevel: "Medium",
    bestTime: "Evening",
    publicRating: 4.6,
    publicImage: "images/tokyo/nakameguro.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },

  // ─── KYOTO (17 locations) ───────────────────────────────────────────────────
  {
    id: 19,
    name: "Fushimi Inari Taisha",
    city: "Kyoto",
    type: "Shrine",
    crowdLevel: "High",
    bestTime: "Morning",
    publicRating: 4.9,
    publicImage: "images/kyoto/fushimi-inari.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 20,
    name: "Arashiyama Bamboo Grove",
    city: "Kyoto",
    type: "Nature",
    crowdLevel: "High",
    bestTime: "Morning",
    publicRating: 4.7,
    publicImage: "images/kyoto/bamboo-grove.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 21,
    name: "Kinkaku-ji (Golden Pavilion)",
    city: "Kyoto",
    type: "Temple",
    crowdLevel: "High",
    bestTime: "Morning",
    publicRating: 4.8,
    publicImage: "images/kyoto/kinkakuji.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 22,
    name: "Gion District",
    city: "Kyoto",
    type: "District",
    crowdLevel: "High",
    bestTime: "Evening",
    publicRating: 4.7,
    publicImage: "images/kyoto/gion.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 23,
    name: "Kiyomizu-dera Temple",
    city: "Kyoto",
    type: "Temple",
    crowdLevel: "High",
    bestTime: "Morning",
    publicRating: 4.8,
    publicImage: "images/kyoto/kiyomizudera.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 24,
    name: "Philosopher's Path",
    city: "Kyoto",
    type: "Nature",
    crowdLevel: "Medium",
    bestTime: "Morning",
    publicRating: 4.6,
    publicImage: "images/kyoto/philosophers-path.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 25,
    name: "Nijo Castle",
    city: "Kyoto",
    type: "Castle",
    crowdLevel: "Medium",
    bestTime: "Morning",
    publicRating: 4.5,
    publicImage: "images/kyoto/nijo-castle.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 26,
    name: "Nishiki Market",
    city: "Kyoto",
    type: "Market",
    crowdLevel: "High",
    bestTime: "Afternoon",
    publicRating: 4.5,
    publicImage: "images/kyoto/nishiki.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 27,
    name: "Tenryu-ji Temple",
    city: "Kyoto",
    type: "Temple",
    crowdLevel: "Medium",
    bestTime: "Morning",
    publicRating: 4.7,
    publicImage: "images/kyoto/tenryuji.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 28,
    name: "Ryoan-ji Rock Garden",
    city: "Kyoto",
    type: "Temple",
    crowdLevel: "Medium",
    bestTime: "Morning",
    publicRating: 4.6,
    publicImage: "images/kyoto/ryoanji.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 29,
    name: "Pontocho Alley",
    city: "Kyoto",
    type: "District",
    crowdLevel: "High",
    bestTime: "Evening",
    publicRating: 4.6,
    publicImage: "images/kyoto/pontocho.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 30,
    name: "Monkey Park Iwatayama",
    city: "Kyoto",
    type: "Nature",
    crowdLevel: "Medium",
    bestTime: "Afternoon",
    publicRating: 4.4,
    publicImage: "images/kyoto/monkey-park.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 31,
    name: "Daitoku-ji Temple Complex",
    city: "Kyoto",
    type: "Temple",
    crowdLevel: "Low",
    bestTime: "Morning",
    publicRating: 4.6,
    publicImage: "images/kyoto/daitokuji.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 32,
    name: "Kurama Onsen",
    city: "Kyoto",
    type: "Onsen",
    crowdLevel: "Low",
    bestTime: "Afternoon",
    publicRating: 4.5,
    publicImage: "images/kyoto/kurama-onsen.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 33,
    name: "Heian Shrine",
    city: "Kyoto",
    type: "Shrine",
    crowdLevel: "Medium",
    bestTime: "Morning",
    publicRating: 4.5,
    publicImage: "images/kyoto/heian-shrine.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 34,
    name: "Tofuku-ji Temple",
    city: "Kyoto",
    type: "Temple",
    crowdLevel: "Medium",
    bestTime: "Morning",
    publicRating: 4.6,
    publicImage: "images/kyoto/tofukuji.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 35,
    name: "Sagano Scenic Railway",
    city: "Kyoto",
    type: "Attraction",
    crowdLevel: "Medium",
    bestTime: "Afternoon",
    publicRating: 4.5,
    publicImage: "images/kyoto/sagano-railway.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },

  // ─── OSAKA (15 locations) ───────────────────────────────────────────────────
  {
    id: 36,
    name: "Dotonbori",
    city: "Osaka",
    type: "District",
    crowdLevel: "High",
    bestTime: "Night",
    publicRating: 4.7,
    publicImage: "images/osaka/dotonbori.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 37,
    name: "Osaka Castle",
    city: "Osaka",
    type: "Castle",
    crowdLevel: "High",
    bestTime: "Morning",
    publicRating: 4.6,
    publicImage: "images/osaka/osaka-castle.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 38,
    name: "Universal Studios Japan",
    city: "Osaka",
    type: "Amusement Park",
    crowdLevel: "High",
    bestTime: "Morning",
    publicRating: 4.7,
    publicImage: "images/osaka/usj.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 39,
    name: "Kuromon Ichiba Market",
    city: "Osaka",
    type: "Market",
    crowdLevel: "High",
    bestTime: "Morning",
    publicRating: 4.5,
    publicImage: "images/osaka/kuromon.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 40,
    name: "Shinsekai District",
    city: "Osaka",
    type: "District",
    crowdLevel: "Medium",
    bestTime: "Evening",
    publicRating: 4.4,
    publicImage: "images/osaka/shinsekai.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 41,
    name: "Sumiyoshi Taisha Shrine",
    city: "Osaka",
    type: "Shrine",
    crowdLevel: "Low",
    bestTime: "Morning",
    publicRating: 4.5,
    publicImage: "images/osaka/sumiyoshi.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 42,
    name: "Tempozan Ferris Wheel",
    city: "Osaka",
    type: "Attraction",
    crowdLevel: "Medium",
    bestTime: "Evening",
    publicRating: 4.3,
    publicImage: "images/osaka/tempozan.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 43,
    name: "Umeda Sky Building",
    city: "Osaka",
    type: "Landmark",
    crowdLevel: "Medium",
    bestTime: "Evening",
    publicRating: 4.5,
    publicImage: "images/osaka/umeda-sky.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 44,
    name: "Namba Parks",
    city: "Osaka",
    type: "City",
    crowdLevel: "Medium",
    bestTime: "Afternoon",
    publicRating: 4.3,
    publicImage: "images/osaka/namba-parks.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 45,
    name: "Osaka Aquarium Kaiyukan",
    city: "Osaka",
    type: "Aquarium",
    crowdLevel: "Medium",
    bestTime: "Afternoon",
    publicRating: 4.6,
    publicImage: "images/osaka/kaiyukan.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 46,
    name: "Den Den Town",
    city: "Osaka",
    type: "District",
    crowdLevel: "Medium",
    bestTime: "Afternoon",
    publicRating: 4.2,
    publicImage: "images/osaka/dendentown.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 47,
    name: "Tsutenkaku Tower",
    city: "Osaka",
    type: "Landmark",
    crowdLevel: "Medium",
    bestTime: "Afternoon",
    publicRating: 4.3,
    publicImage: "images/osaka/tsutenkaku.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 48,
    name: "Shitennoji Temple",
    city: "Osaka",
    type: "Temple",
    crowdLevel: "Low",
    bestTime: "Morning",
    publicRating: 4.4,
    publicImage: "images/osaka/shitennoji.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 49,
    name: "Amerikamura",
    city: "Osaka",
    type: "District",
    crowdLevel: "Medium",
    bestTime: "Afternoon",
    publicRating: 4.2,
    publicImage: "images/osaka/amerikamura.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
  {
    id: 50,
    name: "Nakanoshima Park",
    city: "Osaka",
    type: "Park",
    crowdLevel: "Low",
    bestTime: "Morning",
    publicRating: 4.4,
    publicImage: "images/osaka/nakanoshima.jpg",
    visited: false,
    userRating: null,
    isStarred: false,
    userImages: [],
  },
];